[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "RT-DETR"
version = "0.1"
dependencies = [
    "torch==2.0.1",
    "torchvision==0.15.2",
    "onnx==1.14.0",
    "onnxruntime==1.15.1",
    "pycocotools",
    "PyYAML",
    "scipy"
]
